version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - app_network
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - app_network

networks:
  app_network:
    external: true

volumes:
  db_data:
  db_logs:
