version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: home_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/home_library"
      PORT: 4000
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./dist:/app/dist
    command: npm run start:dev

networks:
  app-network:

volumes:
  postgres_data:
