services:
  app:
    build:
      context: .
    container_name: nestjs_app_c 

    ports:
        - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm run start:dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres 
    networks:
      - custom_network
    entrypoint: /bin/sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    restart: always

  postgres:
    image: postgres:latest 
    container_name: postgres_c
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT_3}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network 
    restart: always


volumes:
  postgres_data:
    driver: local

networks:
  custom_network:
    driver: bridge
